sudo: required
services:
- docker
env:
  global:
  - SHA=$(git rev-parse HEAD)
  - REGISTRY_USER=phoenixking25
before_install:
- openssl aes-256-cbc -K $encrypted_8406ff1e2f87_key -iv $encrypted_8406ff1e2f87_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d

script:
- docker build -t phoenixking25/obscura-frontend .
after_scripts:
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push phoenixking25/obscura-frontend
  on:
    branch: master
